### ISSUE TITLE
Assets List

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#13]
A left side panel to:

- [x] parent of #20 List existing Assets with the possibility to select one of them (to show then the related missions)
- [x] parent of #21 Create a new Asset (a creation form allow to enter the Asset metadata and upload the Asste's geometry if any, the geometry of the Asset is not mandatory)
- [ ] parent of #22 Manage rights on existing/newly created assets (an Asset is a new kind of resource of category ASSET)
- [ ] parent of #23 Search Assets by ROI

**Comment by tdipisa** [comment]
closed for inactivity
