### ISSUE TITLE
Missions List

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#14]
- [x] parent of #24  List existing Missions within the selected Asset with the possibility to select one of them to see the mission path on the map
- [x] parent of #25 A button allows to drill down on the Mission detail panel to see the video and Mission data
- [x] parent of #26 Create a new Mission (a creation form allows to enter the Mission metadata and upload the Mission's files for the ingestion in the backend)
- [ ] parent of #27 Manage rights on existing/newly created missions (a Mission is a new kind of resource of catagory MISSION)
- [x] parent of #28 Search Mission by creation date

**Comment by tdipisa** [comment]
closed for inactivity
