### ISSUE TITLE
Mission Panel

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#15]
- [ ] parent of #29 Show the video of the mission with the possibility to stop, pause, play it

- [x] parent of #30 Show the list of detected anomalies during the mission (Objects previously ingested in the mission creation)
Each Object in the list allows to show the related frame (it will be retrieved from the backend)
Each Object in the list allows to show object point on map

- [x] parent of #31 If the Mission Panel is opened we have to put in map the geometry of the Asses (if available) and the Mission's path

- [x] parent of #32 The drone must be indicated in the map (this can be done using telemetry data)
During the video, the position of the drone is updated on the map using the collected telemetry information.
- [x] parent of #33 We can consider using telemetry information to provide further feedbacks to the user like:
highlight detected anomalies in list
highlight detected anomalies in video frames

**Comment by tdipisa** [comment]
closed for inactivity
