### ISSUE TITLE
Issues found during the integration testing (Round 1)

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C098#59]
- [x] 1) The IT translations are corrupted 
- [x] 2) The drone is not visible in map
- [x] 3) The anomalies are not sorted by time ascending
- [x] 4) The search filter of assets/missions by name should be case insensitive
- [x] 5) The filter by data has some issues: if I clear the filter the list of items must be reset (now the list goes empty and if I set a start date elements the list appears again magically)
- [x] 6) Drop mission zip file, after dropping the zip file the blue zone persists
   - [x] If valid: the blue area must disappear and appear again if I clear the zip dragged previously
   - [x] If invalid: both red area and blu area must be present
- [x] 7) If I modify a mission there are save errors and the operation requires a lot of time to fails. Then if I exit the mission setting to return inside it again the red exclamation point remains visible
- [x] 8) If selected a mission or an asset, the arrow icon should change color
- [x] 9) Implement asset/mission delete (only GeoStore side, remove only the selected object in list, an remove icon should appears in toolbar)
- [x] 10) It must be possible to remove the asset geometry in asset settings
- [x] 11) If the asset type change there's a save error
- [x] 12) When I draw a point geometry for an asset the marker does not appears in the map (the point should be available only for electric truss) 
- [x] 13) After logout and then login the asset list is not loaded (there is a console error). Now if I login as admin the asset loading spinner doesn't go away

**Comment by MV88** [comment]
10 and 11 needs a fix on the backend 
8 is unclear, what is expected exactly? which color should take? what about the button background color?

**Comment by MV88** [comment]
the icon should change the background color to success color
![image](https://user-images.githubusercontent.com/11991428/59700527-c5048900-91f3-11e9-9953-a5cd1a8398f3.png)
